#!/bin/bash

#Final state machine like
state=0
#Installation path
folder="/opt/Cloudify"
#Quality level for the connection
quality=5
#Compression level
compression=2
#Protocol to be used (default VNC)
protocol="vnc"
#Timeout to wait for the pod creation (expressed in seconds)
timeout=60
#Seconds for the server response to consider a good connection
connection_answer_time=1
#The Persistent Volume Claim deployment
pvcDeploy="$folder/kubernetes/volumes.yaml"
#The target deployment file
targetDeploy="$folder/kubernetes/deployment.yaml"
#Variable to select connection type, 0=clear, 1=encrypted
enc=0
#Pulseaudio port
pulsePort=34567
#List of supported apps
supported_apps=("firefox" "libreoffice")
supported_protocols=("vnc" "novnc")

#Set SECURE_CONNECTION to 1/0 depending on encryption
function adjust_encription {
	line=`grep -n 'SECURE_CONNECTION' ${targetDeploy} | cut -d : -f -1`
	((line=line+1))

	sed -i "${line}s/[0-1]/${enc}/" ${targetDeploy}	
}

#Set application name in deployment
function adjust_appname {
	sed -i "s/XXXXXXXXXX/${application_name}/" ${targetDeploy}
}

#Set the new generated token
function adjust_token {
	line=`grep -n 'VNC_PASSWORD' ${targetDeploy} | cut -d : -f -1`
	((line=line+1))
	
	sed -i "${line}s/\".*\"/\"$token\"/" ${targetDeploy}
}

function adjust_volumes {
	from=`grep -n "${application_name}-persistent-storage" ${targetDeploy} | cut -d : -f -1`
	((to=from+1))
	
	sed -i "${from},${to} {s/^#//g}" ${targetDeploy}
}

#Remove services and ports depending on protocol used
function adjust_protocol {
	from_novnc_service=`grep -w -n 'novnc-svc-port' ${targetDeploy} | cut -d : -f -1`
	((till_novnc_service=from_novnc_service+3))
	from_vnc_service=`grep -w -n 'vnc-svc-port' ${targetDeploy} | cut -d : -f -1`
	((till_vnc_service=from_vnc_service+3))
	from_novnc_container=`grep -w -n 'novnc-cont-port' ${targetDeploy} | cut -d : -f -1`
	((till_novnc_container=from_novnc_container+1))
	from_vnc_container=`grep -w -n 'vnc-cont-port' ${targetDeploy} | cut -d : -f -1`
	((till_vnc_container=from_vnc_container+1))
	
	if [[ $enc -eq 1 ]]; then
		sed -i "${from_novnc_container},${till_novnc_container}d;${from_novnc_service},${till_novnc_service}d;${from_vnc_container},${till_vnc_container}d;${from_vnc_service},${till_vnc_service}d" ${targetDeploy}
	elif [ "$protocol" = "vnc" ]; then
		sed -i "${from_novnc_container},${till_novnc_container}d;${from_novnc_service},${till_novnc_service}d" ${targetDeploy}
	else 
		sed -i "${from_vnc_container},${till_vnc_container}d;${from_vnc_service},${till_vnc_service}d" ${targetDeploy}
	fi
}

#Function to wait for the Nodeport to be opened
function scan_node_port {
	for i in seq 1 $timeout; do
		nc -z $targetNodeIp $targetNodePortSsh
		if [ $? -eq 0 ]; then
			return 0
		fi
	done
	return 1
}

#Retrieving the ip, ports, pod name and namespace
function retrieve_pod_info {
	read -r targetNodeIp targetPodName targetPodNamespace <<<$(kubectl get pod -l app=$application_name -o "jsonpath={..status.hostIP} {.items..metadata.name} {.items..metadata.namespace}")
	if [[ $enc -eq 1 ]]; then
		read -r targetNodePortSsh <<<$(kubectl get svc -l app=$application_name -o 'jsonpath={..spec.ports[?(@.name=="ssh-svc-port")].nodePort}')
	else
		read -r targetNodePortProtocol targetNodePortSsh <<<$(kubectl get svc -l app=$application_name -o 'jsonpath={..spec.ports[?(@.name=="'${protocol}'-svc-port")].nodePort} {..spec.ports[?(@.name=="ssh-svc-port")].nodePort}')
	fi
}

#Function to connect to target
function connect {
	#export SSH_ASKPASS="${PWD}/zenity_askpass"

	# Forwarding sound
	ssh -o UserKnownHostsFile=/dev/null -i "${working_dir}/id_rsa" -oStrictHostKeyChecking=no -f -N -R ${pulsePort}:localhost:${pulsePort}  vncuser@${targetNodeIp} -p ${targetNodePortSsh}
	((state=state+1))

	if [ $enc -eq 1 ]; then
		if [ "$protocol" = "vnc" ]; then
			port=5900;
		else
			port=5800;
		fi
		#Creating ssh tunnel for the protocol
		ssh -o UserKnownHostsFile=/dev/null -i "${working_dir}/id_rsa" -oStrictHostKeyChecking=no -f -N -L ${port}:localhost:${port}  vncuser@${targetNodeIp} -p ${targetNodePortSsh}
	fi

	if [ "$protocol" = "vnc" ]; then
		#Check encryption, if yes -> start vnc encrypted connection
		#otherwise -> start normal vnc connection
		if [ $enc -eq 1 ]; then
			echo "Starting encrypted VNC connection..."
			target="localhost::${port}"
		else
			echo -n "Starting clear VNC connection..."
			target="$targetNodeIp::$targetNodePortProtocol"
		fi
		vncviewer -CompressLevel $compression -QualityLevel $quality $target -passwd <(echo ${token} | vncpasswd -f) 2>/dev/null
	else
		if [ $enc -eq 1 ]; then
			echo -n "Starting encrypted NOVnc connection..."
			url="http://localhost:$port"
		else
			echo -n "Starting clear NOVnc connection..."
			url="http://$targetNodeIp:$targetNodePortProtocol"
		fi
		notify-send -t 10000 -a 'Kubernetes on Desktop' "One time Token" "$token"
		firefox $url &>/dev/null
		pid=`pgrep firefox`
		((timeout=timeout*timeout))
		
		timeout $timeout tail --pid=$pid -f /dev/null
	fi
	echo "OK"
}

#Main function to start the deployment of the desired application
function start_deploy {
	#For safety let's copy the deployment and modify the temporary one
	working_dir="/tmp/Cloudify/$(date +%F_%H-%M-%S)"
	mkdir -p $working_dir &>/dev/null
	cp ${targetDeploy} "${working_dir}/deployment.yaml"
	targetDeploy="${working_dir}/deployment.yaml"
	
	adjust_volumes
	adjust_encription
	adjust_appname
	adjust_protocol
	
  #Checking connectivity
  #To perform that task, the command `kubectl describe pods` is used (we could use version, but too fast since tight)
  echo -n "Checking connectivity..."
  nettime=$( TIMEFORMAT="%3U + %3S"; { time timeout 2 kubectl describe pods; } 2>&1)

  if [ $? -eq 0 ]; then
  	#Parsing previous output to get sum of seconds
  	nettime=$(echo ${nettime} | sed 's/,/./g' |  awk '{printf "%f", $1 + $2}')
		
		#Checking network speed availability
		if [[ $(echo "${nettime}<${connection_answer_time}" | bc) -eq 1 ]]; then
			
			echo "OK cluster answered in ${nettime} seconds"
			
			echo -n "Generating token..."
			token=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
			echo "OK"

			adjust_token

			echo -n "Applying deploy..."
			#Start both deploy and volume
  		kubectl apply -f $pvcDeploy &>/dev/null && kubectl apply -f $targetDeploy &>/dev/null
		
			if [ $? -ge 0 ]; then
				echo "OK"
				#Register Ctr+C interrupt
				trap clear_and_exit INT TERM KILL EXIT QUIT HUP
					
				#Generating ssh key pair
				echo -n "Generating ssh key pair..."
				ssh-keygen -t rsa -b 4096 -C "${USER}@kubernetes.io" -f "${working_dir}/id_rsa" -N "" &>/dev/null
				echo "OK"

				echo -n "Loading PulseAudio tcp module..."
				pactl load-module module-native-protocol-tcp port=${pulsePort} auth-ip-acl=127.0.0.1 &>/dev/null
				echo "OK"
				((state=state+1))

				#Waiting for the pod to start
				echo -n "Waiting for pod to start, max ${timeout}seconds..."
				kubectl wait --for=condition=Ready pod -l "app=${application_name}" --timeout=${timeout}s &>/dev/null
	
				if [ $? -eq 0 ]; then
					echo "OK pod running"

					echo -n "Retrieving node IP and PORT..."
					retrieve_pod_info
					echo "OK ip -> ${targetNodeIp}, $protocol -> ${targetNodePortProtocol}, ssh -> ${targetNodePortSsh}, podName -> ${targetPodName}, podNs -> ${targetPodNamespace}"
					
					echo -n "Deploying public key to pod..."
					kubectl cp "${working_dir}/id_rsa.pub" ${targetPodNamespace}/${targetPodName}:/home/vncuser/.ssh/authorized_keys
					echo "OK"

					echo -n "Waiting for the NodePort to be opened..."
					scan_node_port

					if [ $? -eq 0 ]; then
						echo "OK port opened"
						connect
						return
					else
						echo "ERROR Nodeport took too much to be opened, running ${application_name} locally"
					fi
				else
					echo "ERROR cannot create pod, running ${application_name} locally"
				fi
			else
				echo "ERROR cannot apply deployment, running ${application_name} locally"
			fi
		else
			echo "ERROR cluster answered in ${nettime} seconds (too slow), running ${application_name} locally"
		fi
	else
		echo "ERROR no Internet, running ${application_name} locally"
  fi
	${application_name} &>/dev/null &
}

#Delete only the deployment NOT the volume
function clear_and_exit {
	trap - INT TERM KILL EXIT QUIT HUP
	echo -n "Deleting deploy on cluster..."
	kubectl delete -f $targetDeploy &>/dev/null
	echo "OK"
	if [[ $state -ge 1 ]]; then
		echo -n "Unloading PulseAudio TCP module..."
		pactl unload-module module-native-protocol-tcp &>/dev/null
		echo "OK"
	fi
	if [ $state -eq 2 ]; then
		echo -n "Stopping ssh connections..."
		pkill ssh
		echo "OK"
	fi
	exit $1
}

#Print usage function
function print_usage_and_exit {
	echo "Run application in Cloud using Kubernetes as orchestrator."
	echo "Usage: ./cloudify [-h] [-e] [-t timeout] [-p protocol] [-q quality] [-c compression] app_name"
	echo "|-> -h: start the helper menu"
	echo "|-> -e: specify that the connection must be encrypted (0/1, default 0 disabled)"
	echo "|-> -t: connection/wait timeout in seconds (positive number, default $timeout)"
	echo "|-> -p: connection protocol to be used (vnc/novnc, default $protocol)"
	echo "|-> -q: specify the quality of the connection (0-9, default $quality)"
	echo "|-> -c: specify the compression of the connection (0-6, default $compression)"
	echo "|"
	echo "|->Example: ./cloudify firefox"
	echo "|->Example: ./cloudify -q 7 -t 10 -e firefox"
	exit $1
}

function main() {
	#Retrieving the name of the application passed as last argument
	for application_name in $@; do :; done
	asd=1
	if [ $# -lt 1 ] || ! ( IFS=$'\n'; echo "${supported_apps[*]}" ) | grep -qFx "$application_name" &>/dev/null; then
		print_usage_and_exit 1
	fi

	while getopts "hec:q:t:p:" opt; do
  	case $opt in
	    e)
	      enc=1
	      echo "Parameter ENCRYPTION...OK activated"
	      ;;
	    t)
				if [[ ! "$OPTARG" =~ ^[0-9]+$ ]]; then
					print_usage_and_exit 1
				fi
				timeout=$OPTARG
				echo "Parameter TIMEOUT...OK ${timeout}"
	      ;;
	    q)
				if [[ ! "$OPTARG" =~ ^[0-9]$ ]]; then
					print_usage_and_exit 1
				fi
				quality=$OPTARG
				echo "Parameter QUALITY...OK ${quality}"
				;;
			c)
				if [[ ! "$OPTARG" =~ ^[0-6]$ ]]; then
					print_usage_and_exit 1
				fi
				compression=$OPTARG
				echo "Parameter COMPRESSION...OK ${compression}"
				;;
	    h)
				print_usage_and_exit 0
				;;
			p)
				if ! ( IFS=$'\n'; echo "${supported_protocols[*]}" ) | grep -qFx "$OPTARG" &>/dev/null; then
					print_usage_and_exit 1
				fi
				protocol="$OPTARG"
				echo "Parameter PROTOCOL...OK $OPTARG"
				;;
	    \?)
				print_usage_and_exit 1
	      ;;
	  esac
	done

	start_deploy
	clear_and_exit 0
}

main $@