### POD config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: libreoffice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libreoffice
  template:
    metadata:
      labels:
        app: libreoffice
    spec:
      containers:
      - name: libreoffice-kubernetes
        image: s41m0n/libreoffice-kubernetes:enc
        imagePullPolicy: Always
        ports:
        - containerPort: 22
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: libreoffice-service
spec:
  selector:
    app: libreoffice
  ports:
  - name: vnc-port-tcp
    protocol: TCP
    port: 22
    targetPort: 22
    nodePort: 31502
  type: NodePort