### POD config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudoffice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudoffice
  template:
    metadata:
      labels:
        app: cloudoffice
    spec:
      volumes:
      - name: cloudoffice-volume
        hostPath:
          path: /home/s41m0n/Desktop/attempt
      containers:
      - name: libreoffice-kubernetes
        image: s41m0n/libreoffice-kubernetes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5900
        volumeMounts:
        - mountPath: "/usr/attempt"
          name: cloudoffice-volume
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: cloudoffice-service
spec:
  selector:
    app: cloudoffice
  ports:
  - name: vnc-port-tcp
    protocol: TCP
    port: 5900
    targetPort: 5900
    nodePort: 32003
  type: NodePort