#Deployment config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RAR_001_APP_NAME_PID-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RAR_001_APP_NAME_PID
  template:
    metadata:
      labels:
        app: RAR_001_APP_NAME_PID
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: RAR_004_NS_LABEL
                  operator: DoesNotExist
      volumes:
      #Shared memory volume, to avoid crashes
      - name: dshm
        emptyDir:
          medium: Memory
      #Secret containing the ssh public key
      - name: ssh-secret
        secret:
          secretName: RAR_003_SSH_SECRET
      #User home directory
#      - name: RAR_002_APP_NAME-persistent-storage
#        persistentVolumeClaim:
#          claimName: RAR_002_APP_NAME-pv-claim
      containers:
      - name: RAR_001_APP_NAME_PID-kubernetes
        image: liqo/RAR_002_APP_NAME-headless-vnc:latest
        imagePullPolicy: IfNotPresent
        env:
        #Local pod pulse server
        - name: "PULSE_SERVER"
          value: "tcp:localhost:34567"
        #Token password for VNC automatically generated by the script
        - name: "VNC_PASSWORD"
          value: "ECk01SFjMag8ENwDveZRwYrUnnLU1a3e"
        #Encryption parameter true/false
        - name: "SECURE_CONNECTION"
          value: "1"
        ports:
        #noVNC port
        - name: novnc-cont-port 
          containerPort: 5800
        #VNC port
        - name: vnc-cont-port 
          containerPort: 5900
        #SSH port
        - name: ssh-cont-port 
          containerPort: 22
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          #Mounting the secret containing the ssh public key
          - name: ssh-secret
            mountPath: /home/vncuser/ssh_secret
            readOnly: true
          #Firefox PVC claim
#          - name: firefox-persistent-storage
#            mountPath: /home/vncuser/.mozilla
          #Libreoffice PVC claim
#          - name: libreoffice-persistent-storage
#            mountPath: /home/vncuser/Documents
          #Blender PVC claim
#          - name: blender-persistent-storage
#            mountPath: /home/vncuser/Documents
          #CUDA Blender PVC claim
#          - name: cuda-blender-persistent-storage
#            mountPath: /home/vncuser/Documents
        #Set max memory to avoid consumes and ensure minimum resources
        resources:
          limits:
            memory: "512Mi"
      terminationGracePeriodSeconds: 0
---
#Service config
#Substitute RAR_001_APP_NAME_PID with the desired application name
apiVersion: v1
kind: Service
metadata:
  name: RAR_001_APP_NAME_PID-service
  labels:
    app: RAR_001_APP_NAME_PID
spec:
  selector:
    app: RAR_001_APP_NAME_PID
  ports:
  - name: novnc-svc-port
    protocol: TCP
    port: 5800
    targetPort: 5800
  - name: vnc-svc-port
    protocol: TCP
    port: 5900
    targetPort: 5900
  - name: ssh-svc-port
    protocol: TCP
    port: 22
    targetPort: 22
  type: NodePort